events {}

http {
    # CORS
    map $http_origin $cors_origin {
        default $http_origin;
    }

    server {
        listen 15000;

        # CORS headers para todas las respuestas
        add_header Access-Control-Allow-Origin $cors_origin always;
        add_header Access-Control-Allow-Methods "GET, POST, PATCH, DELETE, OPTIONS" always;
        add_header Access-Control-Allow-Headers "Authorization, Content-Type, Accept" always;
        add_header Access-Control-Allow-Credentials true always;

        # Manejar preflight OPTIONS globalmente
        if ($request_method = OPTIONS) {
            return 204;
        }

        # Enrutar peticiones al Identity Service
        location /api/auth/ {
            proxy_pass http://identity-service:15001/api/auth/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Enrutar peticiones al Booking Service
        location /api/booking/ {
            proxy_pass http://booking-service:8003/api/booking/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Enrutar todo lo demás al Frontend (React)
        location / {
            proxy_pass http://frontend:15173/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            # Soporte de WebSockets (Necesario para el Hot Reloading de Vite)
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}
