events {}

http {
    server {
        listen 15000;

        # Enrutar peticiones al Identity Service
        location /api/auth/ {
            proxy_pass http://identity-service:15001/api/auth/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Enrutar todo lo demás al Frontend (React)
        location / {
            proxy_pass http://frontend:15173/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            
            # Soporte de WebSockets (Necesario para el Hot Reloading de Vite)
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}
