version: '3.8'

services:
  identity-service:
    build:
      context: ./services/identity-service
    ports:
      - "15001:15001"
    environment:
      - DATABASE_URL=postgresql://user:pass@db_identity:5432/identity_db
      - JWT_SECRET_KEY=28088ae11d2e1571053fe33386cbfa6e
    depends_on:
      - db_identity
    restart: unless-stopped

  catalog-service:
    build:
      context: ./services/catalog-service
    ports:
      - "15002:15002"
    environment:
      - DATABASE_URL=postgresql://user:pass@db_catalog:5432/catalog_db
      - JWT_SECRET_KEY=28088ae11d2e1571053fe33386cbfa6e
    depends_on:
      - db_catalog
    restart: unless-stopped

  db_identity:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: identity_db
    volumes:
      - identity_data:/var/lib/postgresql/data
    restart: unless-stopped

  db_catalog:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: catalog_db
    volumes:
      - catalog_data:/var/lib/postgresql/data
    restart: unless-stopped

  db_booking:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db_booking
    ports:
      - "15432:5432"
    volumes:
      - db_booking_data:/var/lib/postgresql/data
    restart: unless-stopped

  booking-service:
    build:
      context: ./services/booking-service
    ports:
      - "15003:8003"
    volumes:
      - ./services/booking-service:/app
    env_file:
      - ./services/booking-service/.env.example
      - ./services/booking-service/.env
    depends_on:
      - db_booking
    restart: unless-stopped

  mongo_chat:
    image: mongo:7
    ports:
      - "15017:27017"
    volumes:
      - mongo_chat_data:/data/db
    restart: unless-stopped

  chat-service:
    build:
      context: ./services/chat-service
    ports:
      - "15004:8004"
    volumes:
      - ./services/chat-service:/app
    env_file:
      - ./services/chat-service/.env.example
    depends_on:
      - mongo_chat
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "15173:15173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    restart: unless-stopped

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "15000:15000"
    depends_on:
      - identity-service
      - booking-service
      - catalog-service
      - chat-service
      - frontend
    restart: unless-stopped

volumes:
  identity_data:
  catalog_data:
  frontend_node_modules:
  db_booking_data:
  mongo_chat_data:
